### ISSUE TITLE
Remove notification

### ISSUE THREAD

**Issue by netzmensch** [google/OctoPrint-HeaterTimeout#1]
Hi,

thank you very much for this very cool plugin!

It's a bit annoying that I always get the notification, that the plugin was activated on my printer screen, and that I need to remove them one by one.

![heater_timeout](https://user-images.githubusercontent.com/609699/42995929-6a603810-8c12-11e8-961b-2de422611676.png)

Is it possible to add a setting that these announcements are disabled?

Cheers
Martin

**Comment by precision** [comment]
I don't think this will be too much trouble to add.  I'll take a peek when I get back from traveling.

**Comment by netzmensch** [comment]
Hi, are you back from traveling? Already had some time to have a look at this? :)
